Repository welisonmenezes/sysead, pull requests merged in 2020-05, with the labels that each got.

#34 Complete users close #26
  usuarios/cadastrar.html
  usuarios/editar.html
  usuarios/listar.html
  usuarios/ver.html
Labels: task

#37 Implement UX enhancements to Disciplinas flow
  assets/js/app.js
  disciplinas/cadastrar.html
  disciplinas/editar.html
  disciplinas/listar.html
  disciplinas/ver.html
Labels: task

#39 G forum
  forum/cadastrar.html
  forum/editar.html
  forum/listar.html
  forum/ver.html
Labels: task

#47 UX implementation in the Flow of Periods completed
  periodos/cadastrar.html
  periodos/editar.html
  periodos/listar.html
  periodos/ver.html
Labels: task

#52 Reorder folders structure - close #41
  application/backend/.gitkeep
  application/frontend/.gitkeep
  application/mobile/.gitkeep
  resource/database/model-sysead.mwb
  resource/database/sysead.png
  resource/others/.gitkeep
  resource/prototype/assets/css/styles.css
  resource/prototype/assets/img/javascript-1.png
  resource/prototype/assets/img/logo-ead.png
  resource/prototype/assets/img/logo-ead1.png
  resource/prototype/assets/js/app.js
  resource/prototype/assets/vendors/materialize/materialize.min.css
  resource/prototype/assets/vendors/materialize/materialize.min.js
  resource/prototype/biblioteca/cadastrar.html
  resource/prototype/biblioteca/editar.html
  resource/prototype/biblioteca/listar.html
  resource/prototype/biblioteca/ver.html
  resource/prototype/canais/cadastrar.html
  resource/prototype/canais/editar.html
  resource/prototype/canais/listar.html
  resource/prototype/canais/ver.html
  resource/prototype/disciplinas/cadastrar.html
  resource/prototype/disciplinas/editar.html
  resource/prototype/disciplinas/listar.html
  resource/prototype/disciplinas/ver.html
  resource/prototype/foruns/cadastrar.html
  resource/prototype/foruns/editar.html
  resource/prototype/foruns/listar.html
  resource/prototype/foruns/ver.html
  resource/prototype/grupos/cadastrar.html
  resource/prototype/grupos/editar.html
  resource/prototype/grupos/listar.html
  resource/prototype/grupos/ver.html
  resource/prototype/home.html
  resource/prototype/periodos/cadastrar.html
  resource/prototype/periodos/editar.html
  resource/prototype/periodos/listar.html
  resource/prototype/periodos/ver.html
  resource/prototype/tarefas/cadastrar.html
  resource/prototype/tarefas/editar.html
  resource/prototype/tarefas/listar.html
  resource/prototype/tarefas/ver.html
  resource/prototype/unidades/cadastrar.html
  resource/prototype/unidades/editar.html
  resource/prototype/unidades/listar.html
  resource/prototype/unidades/ver.html
  resource/prototype/usuarios/cadastrar.html
  resource/prototype/usuarios/editar.html
  resource/prototype/usuarios/listar.html
  resource/prototype/usuarios/ver.html
Labels: feature

#55 ux bugs resolved
  resource/prototype/periodos/cadastrar.html
  resource/prototype/periodos/editar.html
  resource/prototype/periodos/listar.html
  resource/prototype/periodos/ver.html
Labels: bug

#60 W implement ux to group flow
  resource/prototype/assets/css/styles.css
  resource/prototype/biblioteca/cadastrar.html
  resource/prototype/biblioteca/editar.html
  resource/prototype/biblioteca/ver.html
  resource/prototype/conteudos/cadastrar.html
  resource/prototype/conteudos/editar.html
  resource/prototype/conteudos/ver.html
  resource/prototype/contextos/cadastrar.html
  resource/prototype/contextos/editar.html
  resource/prototype/contextos/listar.html
  resource/prototype/contextos/ver.html
  resource/prototype/disciplinas/cadastrar.html
  resource/prototype/disciplinas/editar.html
  resource/prototype/disciplinas/ver.html
  resource/prototype/foruns/cadastrar.html
  resource/prototype/foruns/editar.html
  resource/prototype/foruns/ver.html
  resource/prototype/grupos/cadastrar.html
  resource/prototype/grupos/editar.html
  resource/prototype/grupos/listar.html
  resource/prototype/grupos/ver.html
  resource/prototype/home.html
  resource/prototype/unidades/cadastrar.html
  resource/prototype/unidades/editar.html
  resource/prototype/unidades/ver.html
  resource/prototype/usuarios/editar.html
Labels: task

#56 G tasks ux
  resource/prototype/tarefas/cadastrar.html
  resource/prototype/tarefas/editar.html
  resource/prototype/tarefas/listar.html
  resource/prototype/tarefas/ver.html
Labels: task

#66 Create the grades views
  resource/database/model-sysead.mwb
  resource/database/sysead.png
  resource/prototype/home.html
  resource/prototype/notas/listar.html
  resource/prototype/notas/ver.html
Labels: task

#68 Class flow completed, awaiting review
  resource/prototype/home.html
  resource/prototype/tarefas/cadastrar.html
  resource/prototype/turmas/cadastrar.html
  resource/prototype/turmas/editar.html
  resource/prototype/turmas/listar.html
  resource/prototype/turmas/ver.html
Labels: task

#77 Update the database to fit the new flow strategy.
  resource/database/model-sysead.mwb
  resource/database/sysead.png
Labels: task
